
- name: "Add Node.js from Node source"
  become: true
  shell: |
     sudo curl -sL https://deb.nodesource.com/setup_13.x --output nodesjssetup_14.x.sh

- name: "Install Node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm: 
    name: pm2
    global: yes
 