version: 2.1   
orbs:
  slack: circleci/slack@4.9.3
commands:
  notify_on_failure :
    steps:
      - slack/notify:
         event: fail
         channel: cicd-pipelines
         template: basic_fail_1     
jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-deps]
      - run:
          name: Front-end build
          
          command: | 
           cd frontend
           npm install 
           npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-deps
      - notify_on_failure

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-deps]
      - run:
          name: Back-end build
          
          command: | 
           cd backend
           npm install 
           npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-deps
      - notify_on_failure
          
  test-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-deps]
      - run:
          name: Front-end build         
          command: | 
           cd frontend
           npm install 
           npm test          
      - notify_on_failure
                
  test-backend:
      docker:
        - image: cimg/node:13.8.0
      steps:
      - checkout
      - restore_cache:
          keys: [backend-deps]
      - run:
          name: Back-end build         
          command: | 
           cd backend
           npm install 
           npm test
      - notify_on_failure
   
  scan-frontend:
      docker:
       - image: cimg/node:13.8.0
      steps:
       - checkout
       - restore_cache:
          keys: [frontend-deps]
       - run:
          name: Front-end build         
          command: | 
           cd frontend
           npm install 
           npm audit fix --force --audit-level=critical
           npm audit --audit-level=critical
           
       - notify_on_failure

  scan-backend:
    docker:
        - image: cimg/node:13.8.0
    steps:
       - checkout
       - restore_cache:
          keys: [backend-deps]
       - run:
          name: Back-end build         
          command: | 
           cd backend
           npm install 
           npm audit fix --force --audit-level=critical
           npm audit fix --force --audit-level=critical
           npm audit --audit-level=critical
       - notify_on_failure
  notify_on_success:
    docker:
     -image:cimg/base
    steps:
     -slack/notify:
       event: pass
       channel: cicd-pipelines
       template: success_tagged_deployment_1
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]         
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - notify_on_success:
          requires:
            - build-frontend
            - build-backend
            - test-frontend
            - test-backend
      
      
      
      

