version: 2.1

            
jobs:
  build-frontend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-deps]
      - run:
          name: Front-end build
          command: |
           cd frontend
           npm install 
           npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-deps

  build-backend:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-deps]
      - run:
          name: Back-end build
          command: |
           cd frontend
           npm install 
           npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-deps
          
          
    test-frontend:
      docker:
       - image: cimg/node:13.8.0
      steps:
       - checkout
       - restore_cache:
          keys: [frontend-deps]
       - run:
          name: Front-end unit test
          command: |
           cd frontend
           npm install 
           npm test
           
    test-backend:
      docker:
       - image: cimg/node:13.8.0
      steps:
       - checkout
       - restore_cache:
          keys: [backend-deps]
       - run:
          name: Back-end unit test
          command: |
           cd frontend
           npm install 
           npm test
            
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend
      - test-backend
      
